version: "2.2"
services:
  jd-seckill:
    container_name: jd-seckill
    image: jd-seckill
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - docker.env
    volumes:
      - ../jd-seckill:/app
